"""
Setup script for the Data Quality Framework package
"""

from setuptools import setup, find_packages

setup(
    name="spark-truba",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.30.0",
        "pyspark>=3.4.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.2.0",
        "tqdm>=4.65.0",
        "python-dotenv>=1.0.0",
        "textual>=0.40.0",
        "rich>=13.3.3",
        "psutil>=5.9.0",
        "py4j>=0.10.9",
        "pyarrow>=7.0.0",
        "PyYAML>=6.0.1",
        "dataclasses-json>=0.5.7",
        "typing-extensions>=4.0.0",
        "pathlib2>=2.3.7",
        "click>=8.0.4",
        "python-dateutil>=2.8.2",
        "jsonschema>=4.17.3",
        "fastparquet>=0.8.1",
        "python-snappy>=0.6.1",
        "brotli>=1.0.9",
        "lz4>=3.1.3",
        "zstandard>=0.18.0",
        "matplotlib>=3.5.3",
        "seaborn>=0.12.2",
        "plotly>=5.13.0",
        "pytest>=7.0.0",
        "pytest-cov>=4.0.0",
        "black>=22.0.0",
        "flake8>=6.0.0",
        "mypy>=1.0.0",
        "beautifulsoup4>=4.9.3",
        "types-beautifulsoup4>=4.12.0",
        "sentencepiece>=0.1.99",
        "nltk>=3.8.1",
        "datasketch>=1.5.9"
    ],
    python_requires=">=3.8",
    author="Teo",
    author_email="your.email@example.com",
    description="A data quality framework with legal domain filtering",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
    entry_points={
        "console_scripts": [
            "data-quality=data_quality.__main__:main",
        ],
    },
) 